# encoding: UTF-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'rbconfig'
is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)
is_nix = (RUBY_PLATFORM =~ /linux/ or RUBY_PLATFORM =~ /darwin/)

box       = "pp_centos_7_0_vbox"
box_url   = "https://basebox.pixelpark.com/pp_centos_7_0_vbox.box"

nodes = [
  { :hostname => "mp.local", :ip => "192.168.100.144", :ram => 2096},
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = box
      node_config.vm.box_url = box_url
      node_config.vm.hostname = node[:hostname]
      node_config.vm.network :private_network, ip: node[:ip]
      node_config.ssh.forward_agent = true

      node_config.vm.provider :virtualbox do |v|
        memory = node[:ram] ? node[:ram] : 512
        v.customize ["modifyvm", :id, "--name", node[:hostname] + "_" + Time.now.strftime("%s")]
        v.customize ["modifyvm", :id, "--memory", memory.to_s]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end

      if (is_nix)
        node_config.vm.synced_folder "../src", "/var/www", :nfs => true
      end

      node_config.vm.synced_folder "../puppet/hieradata", "/tmp/vagrant-puppet/hieradata", :owner=> 'vagrant', :group=>'vagrant'

      node_config.vm.provision :puppet do |puppet|
        puppet.temp_dir = "/tmp/vagrant-puppet"
        puppet.manifests_path = "../puppet/manifests"
        puppet.manifest_file = "site.pp"
        puppet.module_path = "../puppet/modules"
        puppet.hiera_config_path = "../puppet/hiera.yaml"
        puppet.working_directory = "/tmp/vagrant-puppet"
        puppet.options = "--verbose --trace --summarize"
      end

    if (is_windows)
        node_config.vm.synced_folder "../src", "/var/www/", :smb => true, :owner=> 'vagrant', :group=> 'vagrant', :mount_options => ["dmode=0777,fmode=0666"]

        node_config.vm.provision :puppet do |puppet|
          puppet.manifests_path = "../puppet/manifests"
          puppet.manifest_file = "samba.pp"
          puppet.module_path = "../puppet/modules"
        end
      end
    end
  end
end
